version: '3.3'
services:
  db:
    image: mysql:lasted
    restart: always
    environment:
      MYSQL_DATABASE: 'NexusNode'
      MYSQL_USER: 'dev'
      MYSQL_PASSWORD: '3a8dec982ed29bfc33ded35aaeec0728b50f6f906fd9a7d02b26df45f32e0e81'
      MYSQL_ROOT_PASSWORD: '3a8dec982ed29bfc33ded35aaeec0728b50f6f906fd9a7d02b26df45f32e0e81'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
